version: "3.8"
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.development
    container_name: 
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    ports: 
      - "3000:3000"
