FROM node:lts-alpine

EXPOSE 3000

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

COPY backend/index.js ./backend
COPY frontend/public ./frontend

USER node

ENTRYPOINT [ "npm" , "run", "start" ]
